name: JunonaAI
options:
  bundleIdPrefix: network.montana
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  MontanaCore:
    path: ../../MontanaCore

targets:
  JunonaAI:
    type: application
    platform: iOS
    sources:
      - JunonaAI
    dependencies:
      - package: MontanaCore
      - target: JunonaVPNExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: network.montana.junona
        INFOPLIST_FILE: JunonaAI/Info.plist
        CODE_SIGN_ENTITLEMENTS: JunonaAI/JunonaAI.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: JunonaAI/Info.plist
    entitlements:
      path: JunonaAI/JunonaAI.entitlements

  JunonaVPNExtension:
    type: app-extension
    platform: iOS
    sources:
      - JunonaVPNExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: network.montana.junona.vpn
        INFOPLIST_FILE: JunonaVPNExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: JunonaVPNExtension/JunonaVPNExtension.entitlements
    info:
      path: JunonaVPNExtension/Info.plist
    entitlements:
      path: JunonaVPNExtension/JunonaVPNExtension.entitlements

schemes:
  JunonaAI:
    build:
      targets:
        JunonaAI: all
        JunonaVPNExtension: all
    run:
      config: Debug
