name: MontanaWallet
options:
  bundleIdPrefix: network.montana
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  MontanaCore:
    path: ../../MontanaCore

targets:
  MontanaWallet:
    type: application
    platform: iOS
    sources:
      - MontanaWallet
    dependencies:
      - package: MontanaCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: network.montana.wallet
        INFOPLIST_FILE: MontanaWallet/Info.plist
        CODE_SIGN_ENTITLEMENTS: MontanaWallet/MontanaWallet.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: MontanaWallet/Info.plist
    entitlements:
      path: MontanaWallet/MontanaWallet.entitlements

schemes:
  MontanaWallet:
    build:
      targets:
        MontanaWallet: all
    run:
      config: Debug
